#name: Run arbitrary symfony command
#run-name: Symfony command on server initiated by ${{ github.actor }}
#on:
#    workflow_dispatch:
#        inputs:
#            command:
#                description: 'command, f.e. app:tmp'
#                required: true
#                default: "list"
#jobs:
#    build-bundle-and-upload:
#        runs-on: ubuntu-latest
#        steps:
#            -   name: Setup ssh
#                run: |
#                    mkdir -p ~/.ssh/
#                    echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
#                    chmod 600 ~/.ssh/key
#                    cat >> ~/.ssh/config <<END
#                    Host ${{ secrets.HOST }}
#                        User me
#                        IdentityFile ~/.ssh/key
#                        StrictHostKeyChecking=no
#                    END
#            -   name: Run symfony command
#                run: ssh ${{ secrets.HOST }} 'cd ${{ vars.DEPLOY_DIR }}; ./bin/console ${{ github.event.inputs.command}}'
